title: Simon Knight - Software Developer Portfolio Website
description: Personal portfolio website of Simon Knight.
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed


domain: simondsknight.github.io
url: https://simondsknight.github.io
baseurl: ""
collections:
  projects:
    output: true
    permalink: /projects/:name/
#default front matter for all pages unless overridden
defaults:
  -
    scope: {path: ""}
    values: {layout: "default"}
  - scope: { path: "", type: "projects" }
    values:
      layout: project
site:
  thumb_bg: "#111111"







